[book]
authors = ["Jonathan Kron"]
language = "en"
multilingual = false
src = "src"
title = "Wavefront User Manual"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/AudioGroupCologne/wavefront-manual"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/AudioGroupCologne/wavefront-manual/edit/main/{path}"